server.port=${PORT:8080}
spring.application.name=quma_shopify_backend
spring.security.user.name=quma_admin
spring.security.user.password=quma_p@ssw0rd
spring.data.mongodb.uri=mongodb+srv://quma45:qumaP%40ssw0rd@cluster0.1jtosya.mongodb.net/quma_shopify?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

#########################################       WHATSAPP CONFIGURATIONS         ####################################

#whatsapp.phone-number-id=YOUR_PHONE_NUMBER_ID
whatsapp.access-token=YOUR_ACCESS_TOKEN
whatsapp.api-url=YOUR_API_URL

#########################################        FRONTEND CONFIGURATIONS        #####################################

frontend.redirect.home-url=https://www.yourwebsite.com/home

#########################################          JWT PROPERTIES               #####################################

jwt-secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBnZW5lcmF0ZWQgYnkgS2V5cw==

######################################          REDIS CONFIGURATIONS            #####################################

spring.data.redis.host=brave-yak-31349.upstash.io
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=AXp1AAIncDE0NzViYzdhN2IwODY0MjM4YWY5ZGNmMTg3MjA4NWU1ZXAxMzEzNDk
spring.data.redis.ssl.enabled=true

#####################################            CDN CONFIGURATIONS             #####################################

imagekit.privateKey=private_SEoa+6cqcgh3iUhYC1LkKV2SYHE=
imagekit.publicKey=public_+bzrYESHa0Ueg0HCSUTuPn/TGL0=
imagekit.urlEndpoint=https://ik.imagekit.io/quma

#####################################            ELASTICSEARCH CONFIGURATIONS    ###################################

elasticsearch.url=https://y8n01y4boa:8bp1fhsydu@quma-elastic-5043998993.ap-southeast-2.bonsaisearch.net:443

###################################             RAZORPAY INTEGRATION        #########################

razorpay.key_id=rzp_test_RI0udiXBHfd3lE
razorpay.key_secret=9dC0Hl4HhZQ2GAiW3X8s7aqV
razorpay.webhook_secret=z7ZL2XhR_8d8R5Y

#####################################          ASYNC EXECUTOR CONFIGURATIONS        ###################################

# Thread pool for async analytics tasks
async.analytics.core-pool-size=5
async.analytics.max-pool-size=20
async.analytics.queue-capacity=200
async.analytics.keep-alive-seconds=60
