server.port=${PORT:8080}
spring.application.name=quma_shopify_backend
spring.security.user.name=quma_admin
spring.security.user.password=quma_p@ssw0rd
spring.data.mongodb.uri=mongodb+srv://quma45:qumaP%40ssw0rd@cluster0.1jtosya.mongodb.net/quma_shopify?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true
#####       Whatsapp Configurations         #####
#whatsapp.phone-number-id=YOUR_PHONE_NUMBER_ID
whatsapp.access-token=YOUR_ACCESS_TOKEN
whatsapp.api-url=YOUR_API_URL
#####            Frontend Url            #####
frontend.redirect.home-url=https://www.yourwebsite.com/home
#####            JWT Properties            #####
jwt-secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBnZW5lcmF0ZWQgYnkgS2V5cw==
#####           Redis Configurations          #####
spring.data.redis.host=improved-anemone-62474.upstash.io
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=AfQKAAIjcDFlZjY3NmU2M2U3Nzc0Yzc1ODc1NjgwZmRkNTNiZjJkZXAxMA
spring.data.redis.ssl.enabled=true
